### ISSUE TITLE
SFX_SCRAPPER_SEND_RATE seems ignored

### ISSUE THREAD

**Issue by rata** [signalfx/cadvisor-integration#18]
Hi,

We are testing the integration with kubernetes and the number of metrics with a 4 nodes cluster using only one pod with 3 containers (and the kube-system pods) increased by 6k per minute when using the RC for signalfx integration.

I changed the param in the yam definition to 1m, and when looking at the logs in the pod it seems it is being used:

```
I0405 20:18:51.818648       7 main.go:151] git build commit: ddbd422
I0405 20:18:51.818827       7 main.go:402] Scrapper started with following params:
{
  "IngestURL": "https://ingest.signalfx.com",
  "CadvisorURL": [
    "http://172.20.0.182:4194",
    "http://172.20.0.183:4194",
    "http://172.20.0.185:4194",
    "http://172.20.0.254:4194"
  ],
  "APIToken": "xxx",
  "DataSendRate": "1m",
  "ClusterName": "kube-test",
  "NodeServiceRefreshRate": "5m",
  "CadvisorPort": 4194,
  "KubernetesURL": "",
  "KubernetesUsername": "",
  "KubernetesPassword": ""
}
```

But, when looking at the datapoints per minute sent, after we start the cadvisor-signalfx.yaml RC with 1m send rate, the datapoint still increase 6k per minute.

Is it possible that the setting is not working right (or ignored)?

**Comment by beccatortell** [comment]
Thanks for asking. We're looking into this, and will get back to you shortly.

**Comment by rata** [comment]
@beccatortell thanks, let me know if I can help

**Comment by beccatortell** [comment]
We're able to replicate on our end, and are working on a fix. Will keep you posted. Thanks for reporting!

**Comment by beccatortell** [comment]
Hi there. This issue has been identified and resolved. Please pull in the latest code from this repo and the parameter should behave as you expect.

Previously, DataSendRate controlled only the frequency with which data was delivered, but delivered the same number of datapoints (1 per second), which was not the expected behaviour. This has been corrected. The DataSendRate parameter now functions in the expected manner: it controls the minimum resolution of the data that it sends as well as the frequency with which it is sent. For example, a value of "5m" means that one value will be sent every 5 minutes. This will greatly reduce the data volume sent by this tool to SignalFx.

Thanks again for reporting this issue!

**Comment by rata** [comment]
On Wed, Apr 06, 2016 at 02:53:47PM -0700, beccatortell wrote:

> Hi there. This issue has been identified and resolved. Please pull in the latest code from this repo and the parameter should behave as you expect.
> 
> Previously, DataSendRate controlled only the frequency with which data was delivered, but delivered the same number of datapoints (1 per second), which was not the expected behaviour. This has been corrected. The DataSendRate parameter now functions in the expected manner: it controls the minimum resolution of the data that it sends as well as the frequency with which it is sent. For example, a value of "5m" means that one value will be sent every 5 minutes. This will greatly reduce the data volume sent by this tool to SignalFx.

Great, thanks! I'll try it tomorrow, as it's 8PM here and I'm at home already.

So the 6k increase for data points is like the setting was in "1s", right?
Great, so changing it to 1m in this test cluster should probably be enough :)

> Thanks again for reporting this issue!

Thank you! :)

**Comment by rata** [comment]
Great, I confirm is fixed now!
